/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardBirdIdIndexImport } from './routes/dashboard/$birdId/index'
import { Route as DashboardBirdIdWeightsImport } from './routes/dashboard/$birdId/weights'
import { Route as DashboardBirdIdTrainingsImport } from './routes/dashboard/$birdId/trainings'
import { Route as DashboardBirdIdHuntsImport } from './routes/dashboard/$birdId/hunts'
import { Route as DashboardBirdIdFeedingsImport } from './routes/dashboard/$birdId/feedings'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBirdIdIndexRoute = DashboardBirdIdIndexImport.update({
  path: '/$birdId/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBirdIdWeightsRoute = DashboardBirdIdWeightsImport.update({
  path: '/$birdId/weights',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBirdIdTrainingsRoute = DashboardBirdIdTrainingsImport.update({
  path: '/$birdId/trainings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBirdIdHuntsRoute = DashboardBirdIdHuntsImport.update({
  path: '/$birdId/hunts',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBirdIdFeedingsRoute = DashboardBirdIdFeedingsImport.update({
  path: '/$birdId/feedings',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/$birdId/feedings': {
      id: '/dashboard/$birdId/feedings'
      path: '/$birdId/feedings'
      fullPath: '/dashboard/$birdId/feedings'
      preLoaderRoute: typeof DashboardBirdIdFeedingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/$birdId/hunts': {
      id: '/dashboard/$birdId/hunts'
      path: '/$birdId/hunts'
      fullPath: '/dashboard/$birdId/hunts'
      preLoaderRoute: typeof DashboardBirdIdHuntsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/$birdId/trainings': {
      id: '/dashboard/$birdId/trainings'
      path: '/$birdId/trainings'
      fullPath: '/dashboard/$birdId/trainings'
      preLoaderRoute: typeof DashboardBirdIdTrainingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/$birdId/weights': {
      id: '/dashboard/$birdId/weights'
      path: '/$birdId/weights'
      fullPath: '/dashboard/$birdId/weights'
      preLoaderRoute: typeof DashboardBirdIdWeightsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/$birdId/': {
      id: '/dashboard/$birdId/'
      path: '/$birdId'
      fullPath: '/dashboard/$birdId'
      preLoaderRoute: typeof DashboardBirdIdIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBirdIdFeedingsRoute: typeof DashboardBirdIdFeedingsRoute
  DashboardBirdIdHuntsRoute: typeof DashboardBirdIdHuntsRoute
  DashboardBirdIdTrainingsRoute: typeof DashboardBirdIdTrainingsRoute
  DashboardBirdIdWeightsRoute: typeof DashboardBirdIdWeightsRoute
  DashboardBirdIdIndexRoute: typeof DashboardBirdIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBirdIdFeedingsRoute: DashboardBirdIdFeedingsRoute,
  DashboardBirdIdHuntsRoute: DashboardBirdIdHuntsRoute,
  DashboardBirdIdTrainingsRoute: DashboardBirdIdTrainingsRoute,
  DashboardBirdIdWeightsRoute: DashboardBirdIdWeightsRoute,
  DashboardBirdIdIndexRoute: DashboardBirdIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$birdId/feedings': typeof DashboardBirdIdFeedingsRoute
  '/dashboard/$birdId/hunts': typeof DashboardBirdIdHuntsRoute
  '/dashboard/$birdId/trainings': typeof DashboardBirdIdTrainingsRoute
  '/dashboard/$birdId/weights': typeof DashboardBirdIdWeightsRoute
  '/dashboard/$birdId': typeof DashboardBirdIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$birdId/feedings': typeof DashboardBirdIdFeedingsRoute
  '/dashboard/$birdId/hunts': typeof DashboardBirdIdHuntsRoute
  '/dashboard/$birdId/trainings': typeof DashboardBirdIdTrainingsRoute
  '/dashboard/$birdId/weights': typeof DashboardBirdIdWeightsRoute
  '/dashboard/$birdId': typeof DashboardBirdIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$birdId/feedings': typeof DashboardBirdIdFeedingsRoute
  '/dashboard/$birdId/hunts': typeof DashboardBirdIdHuntsRoute
  '/dashboard/$birdId/trainings': typeof DashboardBirdIdTrainingsRoute
  '/dashboard/$birdId/weights': typeof DashboardBirdIdWeightsRoute
  '/dashboard/$birdId/': typeof DashboardBirdIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/$birdId/feedings'
    | '/dashboard/$birdId/hunts'
    | '/dashboard/$birdId/trainings'
    | '/dashboard/$birdId/weights'
    | '/dashboard/$birdId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/$birdId/feedings'
    | '/dashboard/$birdId/hunts'
    | '/dashboard/$birdId/trainings'
    | '/dashboard/$birdId/weights'
    | '/dashboard/$birdId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/$birdId/feedings'
    | '/dashboard/$birdId/hunts'
    | '/dashboard/$birdId/trainings'
    | '/dashboard/$birdId/weights'
    | '/dashboard/$birdId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/$birdId/feedings",
        "/dashboard/$birdId/hunts",
        "/dashboard/$birdId/trainings",
        "/dashboard/$birdId/weights",
        "/dashboard/$birdId/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/$birdId/feedings": {
      "filePath": "dashboard/$birdId/feedings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/$birdId/hunts": {
      "filePath": "dashboard/$birdId/hunts.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/$birdId/trainings": {
      "filePath": "dashboard/$birdId/trainings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/$birdId/weights": {
      "filePath": "dashboard/$birdId/weights.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/$birdId/": {
      "filePath": "dashboard/$birdId/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
